const authConstants = {
    REQUEST_LOGIN: 'IC::A:REQUEST_LOGIN',
    SUCCESS_LOGIN: 'IC::A:SUCCESS_LOGIN',
    FAILED_LOGIN: 'IC::A:FAILED_LOGIN',

    REQUEST_LOGOUT: 'IC::A:REQUEST_LOGOUT',
    SUCCESS_LOGOUT: 'IC::A:SUCCESS_LOGOUT',
    FAILED_LOGOUT: 'IC::A:FAILED_LOGOUT'
};

export default authConstants;